name: Test Power BI Git Setup

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-git-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Power BI Access Token
        id: get_token
        run: |
          response=$(curl -s -X POST -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials&client_id=${{ secrets.PBI_CLIENT_ID }}&client_secret=${{ secrets.PBI_CLIENT_SECRET }}&scope=https://analysis.windows.net/powerbi/api/.default" \
            https://login.microsoftonline.com/${{ secrets.PBI_TENANT_ID }}/oauth2/v2.0/token)

          echo "ACCESS_TOKEN=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV

      - name: Check Power BI Git Connection
        run: |
          echo "🔍 Checking Git integration in Fabric workspace..."
      
          response=$(curl -s -w "%{http_code}" -o response.json \
            -X GET "https://api.fabric.microsoft.com/v1/workspaces/${{ secrets.PBI_WORKSPACE_ID }}/git/connection" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json")
      
          echo "Status Code: $response"
          echo "Response Body:"
          cat response.json | jq
      
          if [[ "$response" != "200" ]]; then
            echo "❌ Git connection not found or workspace is not a Fabric workspace."
            exit 1
          fi
     
      - name: Get my credentials
        run: |
          echo "🔍 Checking Git integration in Fabric workspace..."
      
          response=$(curl -s -w "%{http_code}" -o response.json \
            -X GET "https://api.fabric.microsoft.com/v1/workspaces/${{ secrets.PBI_WORKSPACE_ID }}/git/myGitCredentials" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json")
      
          echo "Status Code: $response"
          echo "Response Body:"
          cat response.json | jq
      
          if [[ "$response" != "200" ]]; then
            echo "❌ Credentials couldn't be returned."
            exit 1
          fi
          
      - name: Set Git Credentials in Power BI Workspace
        run: |
          echo "🔐 Setting Git credentials..."
      
          payload=$(jq -n --arg token "${{ secrets.PAT }}" '{Provider: "GitHub", accessToken: $token}')
      
          response=$(curl -s -w "%{http_code}" -o patch_response.json -X PATCH \
            "https://api.fabric.microsoft.com/v1/workspaces/${{ secrets.PBI_WORKSPACE_ID }}/git/myGitCredentials" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$payload")
      
          echo "Status Code: $response"
          echo "Response:"
          cat patch_response.json
      
          if [[ "$response" != "200" ]]; then
            echo "🚨 Failed to set Git Credentials!"
            exit 1
          fi
