name: Test Power BI Git Setup

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-git-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Power BI Access Token
        id: get_token
        run: |
          response=$(curl -s -X POST -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials&client_id=${{ secrets.PBI_CLIENT_ID }}&client_secret=${{ secrets.PBI_CLIENT_SECRET }}&scope=https://analysis.windows.net/powerbi/api/.default" \
            https://login.microsoftonline.com/${{ secrets.PBI_TENANT_ID }}/oauth2/v2.0/token)

          echo "ACCESS_TOKEN=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV

      - name: Connect Power BI Workspace to GitHub Repo
        run: |
          echo "🚀 Connecting Power BI workspace to GitHub repository..."
          payload=$(jq -n \
            --arg provider "GitHub" \
            --arg url "https://github.com/dp-benedict/sync_pipeline_demo" \
            --arg branch "gf_reportings" \
            --arg folder "/" \
            '{provider: $provider, url: $url, branch: $branch, folder: $folder}')

          curl -X PATCH "https://api.fabric.microsoft.com/v1/workspaces/${{ secrets.PBI_WORKSPACE_ID }}/git" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$payload"

      - name: Set Git Credentials in Power BI Workspace
        run: |
          echo "🔐 Setting GitHub credentials..."
          payload=$(jq -n --arg token "${{ secrets.GITHUB_PAT }}" '{provider: "GitHub", accessToken: $token}')

          response=$(curl -s -w "%{http_code}" -o patch_response.json -X PATCH \
            "https://api.fabric.microsoft.com/v1/workspaces/${{ secrets.PBI_WORKSPACE_ID }}/git/myGitCredentials" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$payload")

          echo "Status Code: $response"
          echo "Response Body:"
          cat patch_response.json

          if [[ "$response" != "200" ]]; then
            echo "🚨 Failed to set Git Credentials!"
            exit 1
          fi

      - name: Validate Git Credentials
        run: |
          echo "🔍 Checking saved Git Credentials..."
          curl -s -X GET "https://api.fabric.microsoft.com/v1/workspaces/${{ secrets.PBI_WORKSPACE_ID }}/git/myGitCredentials" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" | jq
